### ISSUE TITLE
JS examples not showing

### ISSUE THREAD

**Issue by mo-hobbs** [learn-co-curriculum/phase-0-pac-1-intro#3]
### Canvas Link

https://learning.flatironschool.com/courses/4789/pages/introduction-to-programming-as-conversation?module_item_id=292483

### Concern

JS examples were not working in chrome (just an empty white box- I have a screenshot but dont see where to attach it) but they were visible in safari. let me know if there is anything in my settings i may need to change since I was under the impression we should be using Chrome to go through the Canvas lessons. Thanks!

**Comment by graciemcguire** [comment]
Hi @fortfreedom3 ! I am having trouble recreating your issue in Chrome. That being said, based on your description, it sounds like the issue may be related to your environment setup rather than with the lesson itself or the instructions.

The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either:

Reach out to your instructor (if you've started the program and have an instructor)
Use the #js-prework-support Slack channel (if you're working on the prework)
Use the Pair with a TC feature in Canvas to connect with a Technical Coach on the Academic Success Team
Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
